### ISSUE TITLE
汉化统一问题？

### ISSUE THREAD

**Issue by 3TUSK** [windstories/GregTech5EXP-ChineseLocalization#1]
我比较在意的是这个：
https://ftb.gamepedia.com/Template:Navbox_GregTech_5/zh-cn
因为我同时也是Official FTB Wiki的translator，所以...考虑一下吧。

**Comment by windstories** [comment]
所以，您的意思是汉化的话遵循FTB上的来？（如果我理解对的话）这是肯定的，因为在有旧的标准正确汉化时我必定先用旧的，只有当其有问题时我才会有所修改。

**Comment by 3TUSK** [comment]
不。我是打算照着你的汉化重新修一遍……

**Comment by 3TUSK** [comment]
我这么解释下吧：以往的GT5汉化中可能有潜在的翻译问题，如果有的话，就趁这个机会更正并统一掉...

**Comment by windstories** [comment]
您见笑了，汉化的话想用就用（毕竟我只要求二次发布汉化文件时署名），不过估计也没有什么用处，毕竟我着重修改的是一些没翻译或翻译不精确的内容（大多数是物质名）。既然您这样说了，我会再注意注意原本翻译好的汉化的。

**Comment by 3TUSK** [comment]
嗯，比较在意的是那个Sengir's Holy Plank...

**Comment by windstories** [comment]
就是那个玩梗木板？好的，我会再思考一下。

**Comment by 3TUSK** [comment]
Should not be a question anymore.
